### ISSUE TITLE
Include Application design and deployment strategy

### ISSUE THREAD

**Issue by marianareyesa** [marianareyesa/Team3_SoftwareDevOps#22]
Application design:

- Include UML diagram
- Include sequence diagram for the identified use cases
- Include database diagram
- Include design decisions on 12 factor app principles that apply for the MVP ([The Twelve-Factor App (12factor.net)](https://12factor.net/))
- Deployment strategy
- Include environment design
- Review and take decisions based on [DevOps checklist - Azure Architecture Center | Microsoft Learn](https://learn.microsoft.com/en-us/azure/architecture/checklist/dev-ops)
- Review and take decisions on [DevSecOps with GitHub Security - Azure Architecture Center | Microsoft Learn](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/devsecops-in-github)

**Comment by mmiranda222** [comment]
documented in wiki
