### ISSUE TITLE
Infrastructure security design and pipeline security

### ISSUE THREAD

**Issue by marianareyesa** [marianareyesa/Team3_SoftwareDevOps#28]
Work with Manuela, Karim, and Zaid to design and implement infrastructure security best practices that apply for the MVP

Azure app service:
[Security - Azure App Service | Microsoft Learn](https://learn.microsoft.com/en-us/azure/app-service/overview-security)
[Security recommendations - Azure App Service | Microsoft Learn](https://learn.microsoft.com/en-us/azure/app-service/security-recommendations)
[Azure security baseline for App Service | Microsoft Learn](https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/app-service-security-baseline)

Azure container registry:
[Azure security baseline for Container Registry | Microsoft Learn](https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/container-registry-security-baseline)

Key Vault:
[Azure security baseline for Key Vault | Microsoft Learn](https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/key-vault-security-baseline)

PostgreSQL
[Azure security baseline for Azure Database for PostgreSQL - Flexible Server | Microsoft Learn](https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/azure-database-for-postgresql-flexible-server-security-baseline)

**Comment by mmiranda222** [comment]
design documented in the wiki

**Comment by gretalerer** [comment]
using microsoft defender for cloud native apps
