### ISSUE TITLE
Leverage Microsoft Well Architected framework principles

### ISSUE THREAD

**Issue by marianareyesa** [marianareyesa/Team3_SoftwareDevOps#8]
([Microsoft Azure Well-Architected Framework - Azure Well-Architected Framework | Microsoft Learn](https://learn.microsoft.com/en-us/azure/well-architected/)). 

Choose at least 2 design principles of each section to implement in your MVP:
[Reliability design principles - Microsoft Azure Well-Architected Framework | Microsoft Learn](https://learn.microsoft.com/en-us/azure/well-architected/resiliency/principles)
[Security design principles - Microsoft Azure Well-Architected Framework | Microsoft Learn](https://learn.microsoft.com/en-us/azure/well-architected/security/security-principles)
[Cost optimization design principles - Microsoft Azure Well-Architected Framework | Microsoft Learn](https://learn.microsoft.com/en-us/azure/well-architected/cost/principles)
[Operational excellence design principles - Microsoft Azure Well-Architected Framework | Microsoft Learn](https://learn.microsoft.com/en-us/azure/well-architected/devops/principles)
[Principles of the performance efficiency - Microsoft Azure Well-Architected Framework | Microsoft Learn](https://learn.microsoft.com/en-us/azure/well-architected/scalability/principles)

**Comment by mmiranda222** [comment]
# **Chosen design principles:**
### **1. Reliability Design Principles**
**OKRs in Focus:** Enhance MVP User Experience, Optimize Performance and Reliability

**Selected Principles:**

**Automate Recovery from Failure:** Implement automated failover and recovery processes to ensure minimal service disruption, contributing towards achieving 99.99% uptime.
**Test Recovery Procedures:** Regularly test recovery procedures to guarantee a high level of reliability and responsiveness, thereby decreasing transaction times and improving user experience.

Implementation:

Set up automated failover mechanisms using Azure services like Azure Site Recovery.
Conduct regular disaster recovery drills and use Azure monitoring tools to continuously evaluate the resilience of your application.

### **2. Security Design Principles**
OKRs in Focus: Ensure Robust Security Measures

**Selected Principles:**

**Encrypt Sensitive Data at Rest and in Transit:** Use encryption to secure user data and transactions, reducing security breaches.
**Limit Exposure to Attacks with a Zero-Trust Approach:** Implement a zero-trust security model, including strict access controls and identity verification, to improve customer trust.

Implementation:

Implement Azure’s built-in encryption capabilities for data storage and SSL/TLS for data in transit.
Use Azure Active Directory for identity services and implement role-based access controls.

### **3. Cost Optimization Design Principles**
OKRs in Focus: Expand User Base and Adoption, Optimize Performance and Reliability

**Selected Principles:**

**Right-Size Resources to Meet Needs Efficiently:** Optimize Azure resources to handle the increased load from new users without overspending.
**Budget and Monitor Costs:** Implement cost monitoring and budgeting to control expenses as user base expands.

Implementation:

Use Azure Cost Management tools to monitor resource usage and adjust resource allocation based on demand.
Set up budget alerts and review regular cost reports to stay within financial limits.

### **4. Operational Excellence Design Principles**
OKRs in Focus: Constantly Release New Features, Enhance MVP User Experience

**Selected Principles:**

**Automate to Make Operations More Efficient:** Use automation for continuous integration and deployment of new features.
**Iterate and Improve Through Feedback:** Implement a feedback loop with users to continually improve the MVP based on user insights.

Implementation:

Implement GitHub Actions for CI/CD to automate the deployment of new features.
Use Azure Application Insights for real-time user feedback and performance monitoring.

### **5. Performance Efficiency Design Principles**
OKRs in Focus: Optimize Performance and Reliability, Enhance MVP User Experience

**Selected Principles:**

**Design to Scale Out:** Architect the MVP to efficiently handle an increasing number of transactions and users.
**Use Caching to Improve Performance:** Implement caching to reduce app loading times and enhance responsiveness.

Implementation:

Utilize Azure scalability features like Azure App Service Auto Scaling.
Implement Azure Redis Cache or similar technologies to cache frequently accessed data.
